config/routes.rb
Sistemas::Application.routes.draw do
  
  get "home/inicio"

  root :to => 'home#inicio'
  
  match "/quienes_somos", :to => "home#quienes_somos"
  match "/videos", :to => "home#videos"
  match "/contacto", :to => "home#contacto"
  match "/desarrollo", :to => "home#desarrollo"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def inicio
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
 
  def logo_La_Se
    image_tag("Logo_La_Se.jpg", :size => "140x140", :alt => "Logo Grupo La Senia", :class => "round")
  end  
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contacto.html.erb
<h3>Contacto</h3>

app/views/home/inicio.html.erb
<br />
<center><h2>Grupo musical ' La Seña '</h2></center>
<br />
<h3> Amenizamos todo tipo de evento social:</h3>
<br />
<ul Style = "padding-left: 30px;">
	<li>Bodas</li>
	<li>XV años</li>
	<li>Graduaciones</li>
	<li>Aniversarios</li>
	<li>Eventos especiales</li>
	<li>...</li>
</ul>

<h3> Contamos con un amplio repertorio de diferentes géneros y estilos musicales:</h3>
<br />	
<ul Style = "padding-left: 30px;">
	<li>Cumbia</li>
	<li>Salsa</li>
	<li>Cha cha cha</li>
	<li>Mambo</li>
	<li>Danzón</li>
	<li>Rock & Roll</li>
	<li>Pop</li>
	<li>Duranguense</li>
	<li>Banda</li>
	<li>Instrumental</li>
	<li>...</li>
</ul>

<p>Audio e iluminación profesional y un gran ambiente de alegría, 
	darán a tus eventos ese toque tan especial que nos caracteriza.</p>
	<br />
<p><strong>Ponte en contacto con nosotros y con gusto te atenderemos.</strong></p>

<div style="float: right;"><%= link_to(logo_La_Se, root_path) %></div>

	<!-- <%= link_to "Desarrollo de Sistemas", desarrollo_path, :class => "destaca_button3 round" %>  -->
<br />

app/views/home/quienes_somos.html.erb
<h3>Quienes Somos</h3>
<p>El Departamento de Información y Sistemas es una dependencia que forma parte de la Unidad de
	Planeación, Evaluación y Control Escolar, adscrita a La Subsecretaría de Educación Básica y Normal.</p>
	
<%= image_tag("fotos/Tec1.jpg", :size => "100x100", :alt => "Tecnología", :class => "round derecha") %>
	
<h3>Misión</h3>
<p>Desarrollar, implementar y operar sistemas de información en apoyo a los procesos 
 administrativos, programas, proyectos y servicios de educación básica y normal, 
 así cómo brindar soporte técnico y asesoría sobre tecnologías de la  información y 
 comunicaciones a las unidades administrativas  dependientes de la Subsecretaría de 
 Educación Básica y Normal.</p>
<h3>Visión</h3>
<p>Constituirse en un área (de tecnologías de información y comunicaciones) con una productividad 
	de punta que coadyuve de manera apreciable (importante) al mejoramiento de los servicios 
	educativos de educación básica y normal.</p>

app/views/home/videos.html.erb
<br />
<h3>Videos</h3>
<div style="text-align: center">
	<br />
	<p>Video 1</p>
	<object width="350" height="250">
		<param name="movie" value="http://www.youtube.com/v/KtA3Qy3g7B8" />
		<embed src="http://www.youtube.com/v/KtA3Qy3g7B8"
			type="application/x-shockwave-flash" width="300" height="200">
		</embed>
	</object>

	<br />
	<p>Video 2</p>
	<object width="350" height="250">
		<param name="movie" value="http://www.youtube.com/v/Hkb3VUeM3FM" />
		<embed src="http://www.youtube.com/v/Hkb3VUeM3FM"
			type="application/x-shockwave-flash" width="300" height="200">
		</embed>
	</object>
</div>
<br />

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script src="http://api.html5media.info/1.1.5/html5media.min.js"></script>
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'dhonishow', :media => 'screen' %>

    <!-- Bootstrap -->
<%= stylesheet_link_tag 'bootstrap.min', :media => 'screen' %>
<%= stylesheet_link_tag 'bootstrap-responsive.min', :media=> 'screen' %>
<%= stylesheet_link_tag 'public', :media => 'screen'  %>
<%= stylesheet_link_tag 'jquery.bxslider', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grupo La Seña</title>
  <%= csrf_meta_tags %>
  <%= render 'layouts/stylesheets' %>
<!--  <%= javascript_include_tag('jquery-1.8.2.min') %>  -->
   
    <%= javascript_include_tag('http://code.jquery.com/jquery.js') %>
    <%= javascript_include_tag('bootstrap.min') %>
    <%= javascript_include_tag('jquery.bxslider.min') %>
  
  
</head>
<body>		

    <div class="container round">
      <div class="row">
        <div class="span6 offset3">
          <h2>BxSlider Carrusel con descripción en las imágenes</h2>
          <ul class="bxslider">
          	<li><%= image_tag("fotos/La_Se_9851.jpg", :alt => "La Seña", :size => "565x330") %></li>
          	<li><%= image_tag("fotos/La_Se_AgCal.jpg", :alt => "La Seña", :size => "565x330") %></li>
          	<li><%= image_tag("fotos/La_Se_Esce.jpg", :alt => "La Seña", :size => "565x330") %></li>
          </ul>
        </div>
      </div>
    </div> 

    <script type="text/javascript">
      $(document).ready(function(){
        $(".bxslider").bxSlider({
          mode: 'horizontal',
          auto: true, 
          autoControls: true
          });
        });
    </script>
    	
</body>
</html>